#sample playbook -- To install and configure Apache Server
---
- hosts: appgroup
  user: ansadm
  become: yes
  become_method: sudo
  tasks: 
  - name: 1. Install latest version HTTP/Apache RPMs
    yum: name=httpd state=present
  - name: 2. Start httpd service
    service: name=httpd state=started enabled=yes
  - name: 3. Copy the Standard index.html file
    copy: src=/tmp/index.html dest=/var/www/html/index.html mode=0664
  - name: 4. Add Apache iptable rule
    command: /sbin/iptables -I INPUT 1 -p tcp --dport http -j ACCEPT -m comment --comment "Apache on Port 80"
  - name: 5. Save iptable rule
    command: iptables-save  
